name: Shared Workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-job:
    runs-on: windows-latest
    steps:
      - name: Download artifact
        if: github.repository != 'my-testing-org-for-something-cool/repoB'
        uses: actions/download-artifact@v4
        with:
          name: nexus-summary
      - name: Echo from Repo B
        run: echo "Hello from Repo B!"
      - name: Display contents of artifacts_to_upload.csv
        run: |
            echo "Printing contents of artifacts_to_upload.csv:"
            cat artifacts_to_upload.csv
